### ISSUE TITLE
Question regarding get_or / Dictionary.get

### ISSUE THREAD

**Issue by Incblob** [Eoin-ONeill-Yokai/Godot-Rich-Text-Effect-Test-Project#2]
I was going to write to ask about the get_or() function, but after reading the pull request over on godot i figured out that it should be replaced with env.get()
Just writing to remind you to update the demo if you have the time.  The link in the pull points to here, and the code is outdated.

Thanks for a great project :D

**Comment by Eoin-ONeill-Yokai** [comment]
I will update the demo this weekend. Thanks for the reminder!

**Comment by Eoin-ONeill-Yokai** [comment]
Closing now, this issue is resolved in commit -> 17a1a91070ed04c6df15b8964f03573727c2f84b .
