### ISSUE TITLE
Referencing the custom scripts

### ISSUE THREAD

**Issue by chucklepie** [Eoin-ONeill-Yokai/Godot-Rich-Text-Effect-Test-Project#4]
Sorry, this isn't really an issue more of a 'feature request'.

There are 4 scripts in the richtexteffects folder for the custom effects and  are referenced in the _global_script_classes section of the .godot file and nowhere else in any scene that I can see. I can also delete the 'array' in the custom section of the BBCodeSrc text box in the  Testenvironment scene and it still works.

I've read the entire page (https://docs.godotengine.org/en/stable/tutorials/gui/bbcode_in_richtextlabel.html), and I've read all of the code here, but no idea.

Any chance here or the docs could be updated to describe how you add these magical scripts to the project so they're found by the richtext editor and what purpose those 'Array' entries serve?

Thanks.

**Comment by Eoin-ONeill-Yokai** [comment]
@chucklepie By defining scripts that extend a resource type (RichTextEffect), you are creating a new "resource type" which you can then create in Godot by either right clicking on the file system viewer or by clicking on an empty array entry (which will prompt for resource creation.) See [this documentation](https://docs.godotengine.org/en/stable/getting_started/step_by_step/resources.html) for more details on how resources work. This gives the user the ability to define default-parameters or whatever unique properties an individual text effect might have. Once you've created a resource, you need to make sure to add it to the custom effects array found in the `RichTextLabel` node properties dock. 

I hope that makes sense and will help you move toward the right direction. Admittedly, I had hoped that making the script alone would be enough to get the custom effects to register with the RichTextLabel, but the resource approach was the cleanest Godot-compliant method that would easily get approved.

**Comment by chucklepie** [comment]
Thanks. I'll try again, maybe it'll be easier if I try and create from scratch.
